services:
  server:
    volumes:
      - recordings-nfs:/opt/smart-home/data

volumes:
  recordings-nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,nfsvers=4
      device: ":${NFS_EXPORT}"
