CREATE TABLE IF NOT EXISTS cameras (
    id BIGINT UNSIGNED NOT NULL,
    type TINYINT UNSIGNED NOT NULL COMMENT '0=fixed, 1=PTZ',
    serial_number VARCHAR(128) NOT NULL,
    channels INT UNSIGNED NOT NULL,
    ip VARCHAR(255) NOT NULL,
    rtsp_url VARCHAR(2048) NOT NULL DEFAULT '',
    rtmp_url VARCHAR(2048) NOT NULL DEFAULT '',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_cameras_serial (serial_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
